// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMZzU6VVH-JdrA6bQdMurzb5xqJUazfy4',
    appId: '1:303037056950:web:6e27ea42ae9fc776cf6317',
    messagingSenderId: '303037056950',
    projectId: 'draw-flutter',
    authDomain: 'draw-flutter.firebaseapp.com',
    storageBucket: 'draw-flutter.appspot.com',
    measurementId: 'G-49SPDTDTRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ1f9PVf-pBZunsV3Vo9sSTRfQ9rSHQRU',
    appId: '1:303037056950:android:b838b31b77d940b9cf6317',
    messagingSenderId: '303037056950',
    projectId: 'draw-flutter',
    storageBucket: 'draw-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiEal6wX2g7Vcquzwzvqb3uZRteYA-8LQ',
    appId: '1:303037056950:ios:3a6e1697a3fd1674cf6317',
    messagingSenderId: '303037056950',
    projectId: 'draw-flutter',
    storageBucket: 'draw-flutter.appspot.com',
    iosClientId: '303037056950-omnrc68unsk1a67i0s2cra0s5d0o7joh.apps.googleusercontent.com',
    iosBundleId: 'com.example.drawApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiEal6wX2g7Vcquzwzvqb3uZRteYA-8LQ',
    appId: '1:303037056950:ios:9091a1ec58a94a00cf6317',
    messagingSenderId: '303037056950',
    projectId: 'draw-flutter',
    storageBucket: 'draw-flutter.appspot.com',
    iosClientId: '303037056950-juh2d9et3mru4dj9i230ms4sgaee4esn.apps.googleusercontent.com',
    iosBundleId: 'com.example.drawApp.RunnerTests',
  );
}
